# Generated by Django 4.1 on 2025-10-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_delete_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="id",
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
