# Generated by Django 4.1 on 2025-10-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_alter_userinfo_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
