# Generated by Django 4.1 on 2025-10-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_alter_userinfo_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
